= Personas 

== Persona Positiva: Cliente Leal

image::../assets/images/persona-positiva.avif[Persona Positiva,200,100]

- *Nombre:* Fernando
- *Edad:* 30 años
- *Ocupación:* Diseñador gráfico
- *Motivación:* 
    * Busca un computador para trabajar en su casa
    * Aprovechar descuentos y promociones
    * Obtener asesoramiento en la compra
- *Comportamiento:* 
    * Busca información en la web
    * Compara precios y características
    * Realiza la compra en línea
    * Se comunica con el vendedor para aclarar dudas
- *Necesidades:*
    * Información clara y detallada de los productos
    * Facilidad para comparar precios y características
    * Asesoramiento personalizado
    * Proceso de compra sencillo y seguro


== Persona Negativa: Cliente Desconfiado

image::../assets/images/persona-negativa.avif[Persona Positiva,200,100]

- *Nombre:* Carla
- *Edad:* 45 años
- *Ocupación:* Profesora
- *Motivación:* 
    * Desconfianza en las compras en línea
    * Miedo a ser estafada
    * Preferencia por la compra presencial
- *Comportamiento:*
    * Visita la tienda física para ver los productos
    * Consulta precios en línea
    * Realiza la compra en la tienda física
    * Evita proporcionar información personal en línea
- *Necesidades:*
    * Ver y probar los productos antes de comprar
    * Sentirse segura y protegida en la compra
    * Evitar proporcionar información personal en línea
    * Atención personalizada en la tienda física

== User Journey

[plantuml, user-journey-diagram, png]
----
@startuml
title User Journey - PCFactory

actor Fernando as ClientLeal
actor Carla as ClientDesconfiado

ClientLeal -> Frontend : Busca información de productos
Frontend -> Backend : Consulta API de productos
Backend -> DB : Consulta inventario y descuentos

ClientLeal -> Frontend : Compara productos
Frontend -> Backend : Solicita asistencia por chat
Backend -> DB : Actualiza inventario y stock

ClientLeal -> Frontend : Realiza compra
Frontend -> Backend : Validación de stock
Backend -> DB : Actualización de stock

ClientLeal -> Frontend : Sigue su pedido
Frontend -> Backend : Consulta estado de entrega
Backend -> DB : Registro de pedidos

ClientDesconfiado -> Frontend : Visita tienda física
Frontend -> Backend : Consulta stock en otras sucursales
Backend -> DB : Consulta inventario en tiempo real

ClientDesconfiado -> Frontend : Realiza compra en tienda
Frontend -> Backend : Gestiona transacción
Backend -> DB : Actualización del stock

ClientDesconfiado -> Frontend : Consulta estado de pedido especial
Frontend -> Backend : Información de entrega
Backend -> DB : Actualización de estado
@enduml
----
